[package]
name = "moon-stake"
version = "0.1.0"
description = "Escrow staking for the Moon Rangers collection"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "moon_stake"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = "0.31.1"
anchor-spl = "0.31.1"
