name = "solquicks-points"
main = "src/index.js"
compatibility_date = "2025-09-23"

[vars]
ALLOWED_ORIGINS = "https://solquicks.com,https://www.solquicks.com"
MOON_RANGERS_COLLECTION = "5QuB6vy8181PG9g9SiQD6U7TfvuF9hcP9tAjj5DH79oz"

[[d1_databases]]
binding = "DB"
database_name = "solquicks-points"
database_id = "5084c600-ba8a-4c19-96f6-e795ee8c92c3"
